CREATE TABLE MEMBER (
	MEMBER_NO	NUMBER	NOT NULL,
	ID	VARCHAR2(20)	NOT NULL,
	PW	VARCHAR2(20)	NOT NULL,
	NAME	VARCHAR2(20)	NOT NULL,
	EMAIL	VARCHAR2(40)	NOT NULL,
	PHONE	VARCHAR2(20)	NULL
);

CREATE TABLE PRODUCT (
	PRODUCT_NO	NUMBER	NOT NULL,
	PRODUCT_NAME	VARCHAR2(30)	NULL,
	PRODUCT_PRICE	VARCHAR2(10)	NULL,
	PRODUCT_DESC	VARCHAR2(100)	NULL
);

CREATE TABLE CART_PRODUCT (
	MEMBER_NO	NUMBER	NOT NULL,
	PRODUCT_NO  NUMBER	NOT NULL,
	COUNT	NUMBER	NULL
);

CREATE TABLE ORDER_MEMBER (
	ORDER_NO	NUMBER	NOT NULL,
	MEMBER_NO	NUMBER	NOT NULL,
	ORDER_DATE	DATE	NOT NULL,
	POSTAL_CODE	VARCHAR2(20)	NULL,
	ADDRESS	VARCHAR2(100)	NULL,
	PAYMENT_TOTAL	NUMBER	NOT NULL,
    PAYMENT_METHOD	VARCHAR2(100)	NOT NULL
);

CREATE TABLE ORDER_DETAIL (
	PRODUCT_NO	NUMBER	NOT NULL,
	ORDER_NO	NUMBER	NOT NULL,
	COUNT	NUMBER	NULL
);

ALTER TABLE PRODUCT ADD CONSTRAINT PK_PRODUCT PRIMARY KEY (
	PRODUCT_NO
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	MEMBER_NO
);

ALTER TABLE CART_PRODUCT ADD CONSTRAINT PK_CART_PRODUCT PRIMARY KEY (
	MEMBER_NO,
	PRODUCT_NO
);

ALTER TABLE ORDER_MEMBER ADD CONSTRAINT PK_ORDER_MEMBER PRIMARY KEY (
	ORDER_NO
);

ALTER TABLE ORDER_DETAIL ADD CONSTRAINT PK_ORDER_DETAIL PRIMARY KEY (
	PRODUCT_NO,
    ORDER_NO
);

ALTER TABLE CART_PRODUCT ADD CONSTRAINT FK_MEMBER_TO_CART_PRODUCT_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES MEMBER (
	MEMBER_NO
);

ALTER TABLE CART_PRODUCT ADD CONSTRAINT FK_PRODUCT_TO_CART_PRODUCT_1 FOREIGN KEY (
	PRODUCT_NO
)
REFERENCES PRODUCT (
	PRODUCT_NO
);

ALTER TABLE ORDER_MEMBER ADD CONSTRAINT FK_MEMBER_TO_ORDER_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES MEMBER (
	MEMBER_NO
);

ALTER TABLE ORDER_DETAIL ADD CONSTRAINT FK_PRODUCT_TO_ORDER_DETAIL_1 FOREIGN KEY (
	PRODUCT_NO
)
REFERENCES PRODUCT (
	PRODUCT_NO
);

ALTER TABLE ORDER_DETAIL ADD CONSTRAINT FK_ORDER_TO_ORDER_DETAIL_1 FOREIGN KEY (
	ORDER_NO
)
REFERENCES ORDER_MEMBER (
	ORDER_NO
);

DESC MEMBER;

INSERT INTO MEMBER(MEMBER_NO, ID, PW, NAME, EMAIL, PHONE)
VALUES('1', 'ID1', 'PW1', 'MG', 'ID@PW.COM', '010-0000-0000'
);

SELECT * FROM MEMBER;


INSERT INTO PRODUCT(PRODUCT_NO, PRODUCT_NAME, PRODUCT_PRICE,PRODUCT_DESC)
VALUES('1', 'PROTEIN', 25000, '단백질'
);

SELECT * FROM PRODUCT;

INSERT INTO CART_PRODUCT(MEMBER_NO, PRODUCT_NO, COUNT)
VALUES('1', '1', 2

);

SELECT * FROM CART_PRODUCT;

INSERT INTO ORDER_MEMBER(ORDER_NO, MEMBER_NO, ORDER_DATE, POSTAL_CODE, ADDRESS, PAYMENT_TOTAL, PAYMENT_METHOD)
VALUES('1', '1', '20010106', '123', '대한민국', 25000, '신용카드'
);

SELECT * FROM ORDER_MEMBER;

INSERT INTO ORDER_DETAIL(PRODUCT_NO, ORDER_NO, COUNT)
VALUES('1', '1', 2
);

SELECT * FROM ORDER_DETAIL;


